### ISSUE TITLE
奇怪的问题，ModuleNotFoundError: No module named 'chatlog'

### ISSUE THREAD

**Issue by wutong233** [DingHanyang/chatLog#6]
运行./runs/run.py 报错: ModuleNotFoundError: No module named 'chatlog'

**Comment by DingHanyang** [comment]
你好，项目重构中，可能有一些问题，这两天我会先上传一个稳定版本。不过你这个应该是因为项目结构的问题，建议用IDE(Pycharm之类的打开)

**Comment by byx2020** [comment]
> 你好，项目改造中，可能有一些问题，两个天我会先上传一个稳定版本。不过你这个应该是因为项目结构的问题，建议用IDE（Pycharm之类的打开）

![image](https://user-images.githubusercontent.com/58938653/93288401-55be8000-f80e-11ea-987f-b0e759568b55.png)
我使用了Pycharm打开，仍有此问题

**Comment by DingHanyang** [comment]
> > 你好，项目改造中，可能有一些问题，两个天我会先上传一个稳定版本。不过你这个应该是因为项目结构的问题，建议用IDE（Pycharm之类的打开）
> 
> ![image](https://user-images.githubusercontent.com/58938653/93288401-55be8000-f80e-11ea-987f-b0e759568b55.png)
> 我使用了Pycharm打开，仍有此问题

你好，方便留个联系方式吗，我协助你解决。

**Comment by byx2020** [comment]
> > > 你好，项目改造中，可能有一些问题，两个天我会先上传一个稳定版本。不过你这个应该是因为项目结构的问题，建议用IDE（Pycharm之类的打开）
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58938653/93288401-55be8000-f80e-11ea-987f-b0e759568b55.png)
> > 我使用了Pycharm打开，仍有此问题
> 
> 你好，方便留个联系方式吗，我协助你解决。

好的，我QQ是357994223，麻烦大佬了

**Comment by maple-j** [comment]
这个问题咋解决的大佬

**Comment by byx2020** [comment]
> 这个问题咋解决的大佬

抱歉，由于时间过于久远，具体的细节我已经忘了，不过我记得结果好像是没有解决，建议你可以直接艾特问一下开发者。
